# Generated by Django 5.1.5 on 2025-01-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_empresto',
            new_name='data_emprestimo',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='Livro',
            new_name='livro',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nome_usuário',
            new_name='nome_usuario',
        ),
    ]
