# Generated by Django 5.1.5 on 2025-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_empresto',
            new_name='data_emprestimo',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='Livro',
            new_name='livro',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nome_usuário',
            new_name='nome_usuario',
        ),
    ]
